name: ci-main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - name: version
        run: >-
          APP_SHA=$(git rev-parse --short ${GITHUB_SHA});
          APP_REV=$(git rev-list --tags --max-count=1);
          APP_TAG=$(git describe --tags ${APP_REV} 2> /dev/null || echo 0.0.0);
          APP_VERSION=${APP_TAG}-${APP_SHA};
          echo "APP_SHA=${APP_SHA}" >> ${GITHUB_ENV};
          echo "APP_TAG=${APP_TAG}" >> ${GITHUB_ENV};
          echo "APP_VERSION=${APP_VERSION}" >> ${GITHUB_ENV};
      - name: Build Artifact and Docker Image
        run: >-
          mvn versions:set
          --batch-mode
          --file ./pom.xml
          --define newVersion="${APP_VERSION}";
          mvn clean install spring-boot:build-image
          --batch-mode
          --file ./pom.xml
          --define app.packages.username="${APP_PACKAGES_USERNAME}"
          --define app.packages.password="${APP_PACKAGES_PASSWORD}"
          -Dspring-boot.build-image.imageName="ghcr.io/${{ github.repository }}:${APP_VERSION}";
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:${APP_VERSION}